[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

; --- 1. CẤU HÌNH BỘ NHỚ CHO CHIP N4 (4MB Flash, No PSRAM) ---
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L      
board_build.f_flash = 80000000L     
board_build.flash_mode = dio        
board_upload.flash_size = 4MB       
board_build.partitions = huge_app.csv 

; --- 2. DỌN DẸP CẢNH BÁO "REDEFINED" ---
build_unflags = 
    -D ARDUINO_USB_MODE
    -D ARDUINO_USB_CDC_ON_BOOT

; --- 3. BẬT NATIVE USB ĐỂ IN DEBUG ---
build_flags = 
    -D CORE_DEBUG_LEVEL=3           ; Mức Debug: 3 (Info)
    -D BOARD_HAS_PSRAM=0            ; Tắt PSRAM
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0
    -D ARDUINO_USB_MODE=1           ; BẬT chế độ USB Native (Hardware CDC)
    -D ARDUINO_USB_CDC_ON_BOOT=1    ; ÉP luồng Serial đẩy thẳng ra cáp USB của cậu

upload_speed = 921600
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git